// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandoLogic.Jobs.Api.Data;

#nullable disable

namespace PandoLogic.Jobs.Api.Migrations
{
    [DbContext(typeof(JobContext))]
    [Migration("20220426081105_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PandoLogic.Jobs.Api.Models.JobData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Predicted")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TblJobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = 4,
                            Date = new DateTime(2022, 4, 27, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6359),
                            Predicted = 4,
                            Views = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = 6,
                            Date = new DateTime(2022, 4, 28, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6382),
                            Predicted = 6,
                            Views = 4
                        },
                        new
                        {
                            Id = 3,
                            Active = 0,
                            Date = new DateTime(2022, 4, 29, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6385),
                            Predicted = 12,
                            Views = 3
                        },
                        new
                        {
                            Id = 4,
                            Active = 16,
                            Date = new DateTime(2022, 4, 30, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6387),
                            Predicted = 4,
                            Views = 4
                        },
                        new
                        {
                            Id = 5,
                            Active = 0,
                            Date = new DateTime(2022, 5, 1, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6389),
                            Predicted = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = 24,
                            Date = new DateTime(2022, 5, 2, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6391),
                            Predicted = 6,
                            Views = 6
                        },
                        new
                        {
                            Id = 7,
                            Active = 35,
                            Date = new DateTime(2022, 5, 3, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6393),
                            Predicted = 0,
                            Views = 14
                        },
                        new
                        {
                            Id = 8,
                            Active = 24,
                            Date = new DateTime(2022, 5, 4, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6395),
                            Predicted = 32,
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = 18,
                            Date = new DateTime(2022, 5, 5, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6396),
                            Predicted = 18,
                            Views = 18
                        },
                        new
                        {
                            Id = 10,
                            Active = 10,
                            Date = new DateTime(2022, 5, 6, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6399),
                            Predicted = 20,
                            Views = 20
                        },
                        new
                        {
                            Id = 11,
                            Active = 0,
                            Date = new DateTime(2022, 5, 7, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6400),
                            Predicted = 33,
                            Views = 11
                        },
                        new
                        {
                            Id = 12,
                            Active = 24,
                            Date = new DateTime(2022, 5, 8, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6402),
                            Predicted = 48,
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            Active = 13,
                            Date = new DateTime(2022, 5, 9, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6404),
                            Predicted = 13,
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            Active = 42,
                            Date = new DateTime(2022, 5, 10, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6405),
                            Predicted = 56,
                            Views = 14
                        },
                        new
                        {
                            Id = 15,
                            Active = 45,
                            Date = new DateTime(2022, 5, 11, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6407),
                            Predicted = 30,
                            Views = 45
                        },
                        new
                        {
                            Id = 16,
                            Active = 48,
                            Date = new DateTime(2022, 5, 12, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6408),
                            Predicted = 0,
                            Views = 16
                        },
                        new
                        {
                            Id = 17,
                            Active = 0,
                            Date = new DateTime(2022, 5, 13, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6410),
                            Predicted = 34,
                            Views = 51
                        },
                        new
                        {
                            Id = 18,
                            Active = 54,
                            Date = new DateTime(2022, 5, 14, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6412),
                            Predicted = 18,
                            Views = 0
                        },
                        new
                        {
                            Id = 19,
                            Active = 76,
                            Date = new DateTime(2022, 5, 15, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6414),
                            Predicted = 38,
                            Views = 19
                        },
                        new
                        {
                            Id = 20,
                            Active = 100,
                            Date = new DateTime(2022, 5, 16, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6415),
                            Predicted = 80,
                            Views = 40
                        },
                        new
                        {
                            Id = 21,
                            Active = 21,
                            Date = new DateTime(2022, 5, 17, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6417),
                            Predicted = 21,
                            Views = 63
                        },
                        new
                        {
                            Id = 22,
                            Active = 88,
                            Date = new DateTime(2022, 5, 18, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6418),
                            Predicted = 22,
                            Views = 0
                        },
                        new
                        {
                            Id = 23,
                            Active = 115,
                            Date = new DateTime(2022, 5, 19, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6420),
                            Predicted = 23,
                            Views = 23
                        },
                        new
                        {
                            Id = 24,
                            Active = 0,
                            Date = new DateTime(2022, 5, 20, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6421),
                            Predicted = 72,
                            Views = 72
                        },
                        new
                        {
                            Id = 25,
                            Active = 50,
                            Date = new DateTime(2022, 5, 21, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6423),
                            Predicted = 100,
                            Views = 25
                        },
                        new
                        {
                            Id = 26,
                            Active = 26,
                            Date = new DateTime(2022, 5, 22, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6424),
                            Predicted = 52,
                            Views = 52
                        },
                        new
                        {
                            Id = 27,
                            Active = 108,
                            Date = new DateTime(2022, 5, 23, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6425),
                            Predicted = 108,
                            Views = 54
                        },
                        new
                        {
                            Id = 28,
                            Active = 84,
                            Date = new DateTime(2022, 5, 24, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6427),
                            Predicted = 0,
                            Views = 56
                        },
                        new
                        {
                            Id = 29,
                            Active = 0,
                            Date = new DateTime(2022, 5, 25, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6428),
                            Predicted = 87,
                            Views = 29
                        },
                        new
                        {
                            Id = 30,
                            Active = 30,
                            Date = new DateTime(2022, 5, 26, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6430),
                            Predicted = 120,
                            Views = 60
                        },
                        new
                        {
                            Id = 31,
                            Active = 31,
                            Date = new DateTime(2022, 5, 27, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6432),
                            Predicted = 93,
                            Views = 62
                        },
                        new
                        {
                            Id = 32,
                            Active = 0,
                            Date = new DateTime(2022, 5, 28, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6433),
                            Predicted = 128,
                            Views = 32
                        },
                        new
                        {
                            Id = 33,
                            Active = 0,
                            Date = new DateTime(2022, 5, 29, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6434),
                            Predicted = 99,
                            Views = 99
                        },
                        new
                        {
                            Id = 34,
                            Active = 34,
                            Date = new DateTime(2022, 5, 30, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6437),
                            Predicted = 102,
                            Views = 34
                        },
                        new
                        {
                            Id = 35,
                            Active = 105,
                            Date = new DateTime(2022, 5, 31, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6438),
                            Predicted = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = 36,
                            Active = 108,
                            Date = new DateTime(2022, 6, 1, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6440),
                            Predicted = 108,
                            Views = 0
                        },
                        new
                        {
                            Id = 37,
                            Active = 148,
                            Date = new DateTime(2022, 6, 2, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6442),
                            Predicted = 111,
                            Views = 0
                        },
                        new
                        {
                            Id = 38,
                            Active = 114,
                            Date = new DateTime(2022, 6, 3, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6443),
                            Predicted = 114,
                            Views = 38
                        },
                        new
                        {
                            Id = 39,
                            Active = 156,
                            Date = new DateTime(2022, 6, 4, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6445),
                            Predicted = 117,
                            Views = 0
                        },
                        new
                        {
                            Id = 40,
                            Active = 40,
                            Date = new DateTime(2022, 6, 5, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6447),
                            Predicted = 120,
                            Views = 120
                        },
                        new
                        {
                            Id = 41,
                            Active = 205,
                            Date = new DateTime(2022, 6, 6, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6448),
                            Predicted = 123,
                            Views = 123
                        },
                        new
                        {
                            Id = 42,
                            Active = 84,
                            Date = new DateTime(2022, 6, 7, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6450),
                            Predicted = 168,
                            Views = 0
                        },
                        new
                        {
                            Id = 43,
                            Active = 215,
                            Date = new DateTime(2022, 6, 8, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6451),
                            Predicted = 172,
                            Views = 43
                        },
                        new
                        {
                            Id = 44,
                            Active = 88,
                            Date = new DateTime(2022, 6, 9, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6453),
                            Predicted = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = 45,
                            Active = 225,
                            Date = new DateTime(2022, 6, 10, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6454),
                            Predicted = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = 46,
                            Active = 230,
                            Date = new DateTime(2022, 6, 11, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6456),
                            Predicted = 46,
                            Views = 92
                        },
                        new
                        {
                            Id = 47,
                            Active = 94,
                            Date = new DateTime(2022, 6, 12, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6458),
                            Predicted = 47,
                            Views = 94
                        },
                        new
                        {
                            Id = 48,
                            Active = 96,
                            Date = new DateTime(2022, 6, 13, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6459),
                            Predicted = 96,
                            Views = 144
                        },
                        new
                        {
                            Id = 49,
                            Active = 245,
                            Date = new DateTime(2022, 6, 14, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6461),
                            Predicted = 98,
                            Views = 49
                        },
                        new
                        {
                            Id = 50,
                            Active = 250,
                            Date = new DateTime(2022, 6, 15, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6462),
                            Predicted = 200,
                            Views = 100
                        },
                        new
                        {
                            Id = 51,
                            Active = 204,
                            Date = new DateTime(2022, 6, 16, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6464),
                            Predicted = 0,
                            Views = 153
                        },
                        new
                        {
                            Id = 52,
                            Active = 52,
                            Date = new DateTime(2022, 6, 17, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6465),
                            Predicted = 104,
                            Views = 156
                        },
                        new
                        {
                            Id = 53,
                            Active = 0,
                            Date = new DateTime(2022, 6, 18, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6467),
                            Predicted = 212,
                            Views = 0
                        },
                        new
                        {
                            Id = 54,
                            Active = 54,
                            Date = new DateTime(2022, 6, 19, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6468),
                            Predicted = 0,
                            Views = 54
                        },
                        new
                        {
                            Id = 55,
                            Active = 165,
                            Date = new DateTime(2022, 6, 20, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6470),
                            Predicted = 165,
                            Views = 55
                        },
                        new
                        {
                            Id = 56,
                            Active = 56,
                            Date = new DateTime(2022, 6, 21, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6471),
                            Predicted = 168,
                            Views = 168
                        },
                        new
                        {
                            Id = 57,
                            Active = 228,
                            Date = new DateTime(2022, 6, 22, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6473),
                            Predicted = 57,
                            Views = 171
                        },
                        new
                        {
                            Id = 58,
                            Active = 174,
                            Date = new DateTime(2022, 6, 23, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6474),
                            Predicted = 58,
                            Views = 0
                        },
                        new
                        {
                            Id = 59,
                            Active = 0,
                            Date = new DateTime(2022, 6, 24, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6476),
                            Predicted = 118,
                            Views = 59
                        },
                        new
                        {
                            Id = 60,
                            Active = 240,
                            Date = new DateTime(2022, 6, 25, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6477),
                            Predicted = 180,
                            Views = 180
                        },
                        new
                        {
                            Id = 61,
                            Active = 244,
                            Date = new DateTime(2022, 6, 26, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6479),
                            Predicted = 0,
                            Views = 61
                        },
                        new
                        {
                            Id = 62,
                            Active = 0,
                            Date = new DateTime(2022, 6, 27, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6481),
                            Predicted = 62,
                            Views = 62
                        },
                        new
                        {
                            Id = 63,
                            Active = 63,
                            Date = new DateTime(2022, 6, 28, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6482),
                            Predicted = 0,
                            Views = 0
                        },
                        new
                        {
                            Id = 64,
                            Active = 0,
                            Date = new DateTime(2022, 6, 29, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6484),
                            Predicted = 128,
                            Views = 0
                        },
                        new
                        {
                            Id = 65,
                            Active = 325,
                            Date = new DateTime(2022, 6, 30, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6485),
                            Predicted = 130,
                            Views = 130
                        },
                        new
                        {
                            Id = 66,
                            Active = 198,
                            Date = new DateTime(2022, 7, 1, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6488),
                            Predicted = 264,
                            Views = 198
                        },
                        new
                        {
                            Id = 67,
                            Active = 268,
                            Date = new DateTime(2022, 7, 2, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6489),
                            Predicted = 134,
                            Views = 67
                        },
                        new
                        {
                            Id = 68,
                            Active = 340,
                            Date = new DateTime(2022, 7, 3, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6491),
                            Predicted = 272,
                            Views = 136
                        },
                        new
                        {
                            Id = 69,
                            Active = 345,
                            Date = new DateTime(2022, 7, 4, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6492),
                            Predicted = 138,
                            Views = 69
                        },
                        new
                        {
                            Id = 70,
                            Active = 140,
                            Date = new DateTime(2022, 7, 5, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6494),
                            Predicted = 70,
                            Views = 210
                        },
                        new
                        {
                            Id = 71,
                            Active = 284,
                            Date = new DateTime(2022, 7, 6, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6495),
                            Predicted = 213,
                            Views = 213
                        },
                        new
                        {
                            Id = 72,
                            Active = 216,
                            Date = new DateTime(2022, 7, 7, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6497),
                            Predicted = 288,
                            Views = 216
                        },
                        new
                        {
                            Id = 73,
                            Active = 0,
                            Date = new DateTime(2022, 7, 8, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6498),
                            Predicted = 73,
                            Views = 0
                        },
                        new
                        {
                            Id = 74,
                            Active = 74,
                            Date = new DateTime(2022, 7, 9, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6500),
                            Predicted = 148,
                            Views = 222
                        },
                        new
                        {
                            Id = 75,
                            Active = 75,
                            Date = new DateTime(2022, 7, 10, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6501),
                            Predicted = 300,
                            Views = 150
                        },
                        new
                        {
                            Id = 76,
                            Active = 228,
                            Date = new DateTime(2022, 7, 11, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6503),
                            Predicted = 0,
                            Views = 152
                        },
                        new
                        {
                            Id = 77,
                            Active = 77,
                            Date = new DateTime(2022, 7, 12, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6504),
                            Predicted = 231,
                            Views = 231
                        },
                        new
                        {
                            Id = 78,
                            Active = 78,
                            Date = new DateTime(2022, 7, 13, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6506),
                            Predicted = 156,
                            Views = 0
                        },
                        new
                        {
                            Id = 79,
                            Active = 237,
                            Date = new DateTime(2022, 7, 14, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6507),
                            Predicted = 237,
                            Views = 79
                        },
                        new
                        {
                            Id = 80,
                            Active = 240,
                            Date = new DateTime(2022, 7, 15, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6509),
                            Predicted = 80,
                            Views = 240
                        },
                        new
                        {
                            Id = 81,
                            Active = 243,
                            Date = new DateTime(2022, 7, 16, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6511),
                            Predicted = 324,
                            Views = 81
                        },
                        new
                        {
                            Id = 82,
                            Active = 246,
                            Date = new DateTime(2022, 7, 17, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6512),
                            Predicted = 246,
                            Views = 246
                        },
                        new
                        {
                            Id = 83,
                            Active = 83,
                            Date = new DateTime(2022, 7, 18, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6514),
                            Predicted = 332,
                            Views = 83
                        },
                        new
                        {
                            Id = 84,
                            Active = 420,
                            Date = new DateTime(2022, 7, 19, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6515),
                            Predicted = 84,
                            Views = 0
                        },
                        new
                        {
                            Id = 85,
                            Active = 170,
                            Date = new DateTime(2022, 7, 20, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6517),
                            Predicted = 255,
                            Views = 170
                        },
                        new
                        {
                            Id = 86,
                            Active = 430,
                            Date = new DateTime(2022, 7, 21, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6518),
                            Predicted = 258,
                            Views = 172
                        },
                        new
                        {
                            Id = 87,
                            Active = 261,
                            Date = new DateTime(2022, 7, 22, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6520),
                            Predicted = 261,
                            Views = 261
                        },
                        new
                        {
                            Id = 88,
                            Active = 440,
                            Date = new DateTime(2022, 7, 23, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6521),
                            Predicted = 88,
                            Views = 0
                        },
                        new
                        {
                            Id = 89,
                            Active = 0,
                            Date = new DateTime(2022, 7, 24, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6523),
                            Predicted = 178,
                            Views = 178
                        },
                        new
                        {
                            Id = 90,
                            Active = 90,
                            Date = new DateTime(2022, 7, 25, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6524),
                            Predicted = 180,
                            Views = 0
                        },
                        new
                        {
                            Id = 91,
                            Active = 273,
                            Date = new DateTime(2022, 7, 26, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6526),
                            Predicted = 364,
                            Views = 182
                        },
                        new
                        {
                            Id = 92,
                            Active = 92,
                            Date = new DateTime(2022, 7, 27, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6527),
                            Predicted = 276,
                            Views = 276
                        },
                        new
                        {
                            Id = 93,
                            Active = 372,
                            Date = new DateTime(2022, 7, 28, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6529),
                            Predicted = 372,
                            Views = 0
                        },
                        new
                        {
                            Id = 94,
                            Active = 282,
                            Date = new DateTime(2022, 7, 29, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6530),
                            Predicted = 0,
                            Views = 282
                        },
                        new
                        {
                            Id = 95,
                            Active = 380,
                            Date = new DateTime(2022, 7, 30, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6532),
                            Predicted = 190,
                            Views = 285
                        },
                        new
                        {
                            Id = 96,
                            Active = 384,
                            Date = new DateTime(2022, 7, 31, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6533),
                            Predicted = 96,
                            Views = 192
                        },
                        new
                        {
                            Id = 97,
                            Active = 194,
                            Date = new DateTime(2022, 8, 1, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6535),
                            Predicted = 291,
                            Views = 194
                        },
                        new
                        {
                            Id = 98,
                            Active = 490,
                            Date = new DateTime(2022, 8, 2, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6536),
                            Predicted = 392,
                            Views = 196
                        },
                        new
                        {
                            Id = 99,
                            Active = 495,
                            Date = new DateTime(2022, 8, 3, 11, 11, 5, 265, DateTimeKind.Local).AddTicks(6538),
                            Predicted = 99,
                            Views = 297
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
